FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true  
ENV ASPNETCORE_URLS=http://+:5000 
EXPOSE 5000

WORKDIR /src
COPY . /src/
RUN dotnet restore "notify-bg.csproj"
ENTRYPOINT ["dotnet", "run", "--no-launch-profile"]